### ISSUE TITLE
Request for advice

### ISSUE THREAD

**Issue by tamere-allo-peter** [opt-nc/yamlfixer#1]
@adriens Could you give it a look please ? Details in Teams...

**Comment by adriens** [comment]
I'm playing with the tool and will make you feedbacks, each one as an issue 🚀

**Comment by tamere-allo-peter** [comment]
Wonderful ! If only I could work on this right now ;)

**Comment by adriens** [comment]
This is now a part of the collaboration process, check PRs and issues @tamere-allo-peter .

I'm closing the issue
