### ISSUE TITLE
🧑‍🎓 Create a dedicated katacoda scenario

### ISSUE THREAD

**Issue by adriens** [opt-nc/yamlfixer#10]
related to #3

**Comment by adriens** [comment]
# Feedback

@tamere-allo-peter , I've started to prepare some demo scripts, but I'm encoutering some issues. Please find details below 👇 

```
git clone https://github.com/opt-nc/yamlfixer
cd yamlfixer
cp yamlfixer /usr/local/bin
chmod 0755 /usr/local/bin/yamlfixer
```

Now, give it a try : 

```
yamlfixer --version
```

I got the following error message : 


```
  File "/usr/local/bin/yamlfixer", line 107
    self.ffixer.yfixer.debug(f"Calling {methodname} because [{fixerkey}] matches [{self.problem}]")
                                                                                                 ^
SyntaxError: invalid syntax
```

Any idea what's wrong on my environment ❔ 🙏

**Comment by tamere-allo-peter** [comment]
Sure :

```
jerome@OPT17844:~/yamlfixer$ python3 yamlfixer --version
yamlfixer v0.1.1
jerome@OPT17844:~/yamlfixer$ 
jerome@OPT17844:~/yamlfixer$ python2 yamlfixer --version
  File "yamlfixer", line 107
    self.ffixer.yfixer.debug(f"Calling {methodname} because [{fixerkey}] matches [{self.problem}]")
                                                                                                 ^
SyntaxError: invalid syntax
jerome@OPT17844:~/yamlfixer$ 
```

**Comment by adriens** [comment]
Thanks !

**Comment by tamere-allo-peter** [comment]
@adriens : would you like for the code to fail early if Python's version is too old ?

**Comment by adriens** [comment]
Now got a bit further but got following error message : 

```ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall
````


![image](https://user-images.githubusercontent.com/5235127/157776451-1c68bb1e-1012-4e70-b419-3eb05c37f1c8.png)

**Comment by adriens** [comment]
Still it seems to work 

![image](https://user-images.githubusercontent.com/5235127/157776764-3da6c4e2-6878-4162-bce9-b8fe87aee808.png)

**Comment by adriens** [comment]
Givig it a try on a yaml ...

**Comment by tamere-allo-peter** [comment]
@adriens : maybe yamllint won't work

**Comment by tamere-allo-peter** [comment]
@adriens in any case yamlfixer's shebang lines expects it to be launch with python3, but it seems on your system "/usr/bin/env python3" returns python2, otherwise launching /usr/local/bin/yamlfixer without preceding it with the python interpreter wouldn't have failed as it did when you reported the problem, I think.

**Comment by adriens** [comment]
Got it I have a running version on `Ubuntu 20.04.4 LTS \n \l`

**Comment by adriens** [comment]
```
$ yamlfixer --verbose *.yml 
Fixing /root/yamlfixer/bad.yml ... was skipped.
Fixing /root/yamlfixer/demo.yml ... was skipped.
Files to fix: 2
0 files successfully passed yamllint strict mode
0 files were modified
0 files were left unmodified
2 files were skipped
0 files were not writeable
0 files with unknown status
```

**Comment by adriens** [comment]
What should I do so they don't get skipped ?

**Comment by tamere-allo-peter** [comment]
@adriens ensure they contain YAML formatting problems, and that these formatting problems can be fixed by yamlfixer. Files are skipped if yamlfixer doesn't modify them, and it only modifies files if it knows how to do.

**Comment by adriens** [comment]
So here is `bad.yml` :

```yaml
 doe: "a deer, a female deer"
 ray: "a drop of golden sun"
 pi: 3.14159
 xmas: true
 french-hens: 3
 calling-birds:
   - huey
   - dewey
   - louie
   - fred
 xmas-fifth-day:
   calling-birds: four
   french-hens: 3
   golden-rings: 5
   partridges:
     count: 1
     location: "a pear tree"
   turtle-doves: two
   ```

So I get that : 

```
$ yamlfixer --verbose bad.yml 
Fixing /root/yamlfixer/bad.yml ... was skipped.
Files to fix: 1
0 files successfully passed yamllint strict mode
0 files were modified
0 files were left unmodified
1 files were skipped
0 files were not writeable
0 files with unknown status
```

**Comment by tamere-allo-peter** [comment]
Please attach the file, because when I copy&paste then feed yamlfixer the file is not skipped.

**Comment by tamere-allo-peter** [comment]
@adriens : remember, yamlfixer can't fix all problems, in part due to yamllint not reporting all of them.

**Comment by adriens** [comment]
Working on it

**Comment by adriens** [comment]
Working on #13

**Comment by adriens** [comment]
cf  #15

**Comment by adriens** [comment]
Ok, now that we have some demo samples (cf #13 ), here are the output.

To test drive theses, just pull `main` and you're done.

# 1️⃣  Checking "good" `yaml`

```
yamlfixer --verbose examples/good.yml
```

leads to : 

```
Fixing /root/yamlfixer/examples/good.yml ... was skipped.
Files to fix: 1
0 files successfully passed yamllint strict mode
0 files were modified
1 files were skipped
0 files were not writeable
0 files with unknown status
```


# 2️⃣ Checking "bad" `yaml`

```
yamlfixer --verbose examples/bad.yml
```

leads to : 

```
Fixing /root/yamlfixer/examples/bad.yml ... was skipped.
Files to fix: 1
0 files successfully passed yamllint strict mode
0 files were modified
1 files were skipped
0 files were not writeable
0 files with unknown status
```

# 👇 Remarks

Both outputs are the same while `examples/bad.yml` should be flagged fomr my understaning : 

![image](https://user-images.githubusercontent.com/5235127/158079316-0b5760d4-7cef-4107-a9e7-5dba3acd3a2f.png)


# ❔ Question

- What's going wrong with my comand lines
- What should I do to get warned about `bad.yml`
- What should I do to get the fixed version of `bad.yml` (ie. get the yaml fixed as an output... and put it in `fixed-bad.yml`) ❔ 

Thank you for your help @tamere-allo-peter 🙏

**Comment by tamere-allo-peter** [comment]
@adriens something fishy on your computer :

```
jerome@OPT17844:~/yamlfixer$ cp -r examples xx
jerome@OPT17844:~/yamlfixer$ ./yamlfixer --verbose xx/good.yml 
Fixing /home/jerome/yamlfixer/xx/good.yml ... passed linter's strict mode.
Files to fix: 1
1 files successfully passed yamllint strict mode
0 files were modified
0 files were skipped
0 files were not writeable
0 files with unknown status
jerome@OPT17844:~/yamlfixer$ ./yamlfixer --verbose xx/bad.yml 
Fixing /home/jerome/yamlfixer/xx/bad.yml ... was modified.
Files to fix: 1
0 files successfully passed yamllint strict mode
1 files were modified
0 files were skipped
0 files were not writeable
0 files with unknown status
jerome@OPT17844:~/yamlfixer$ 
```

**Comment by tamere-allo-peter** [comment]
@adriens could you launch again with --debug please ?

**Comment by tamere-allo-peter** [comment]
@adriens : my guess is that yamllint is nowhere to be found in your `$PATH` or, more probably, that it fails even before parsing the files.

Could you paste the output of `which yamllint` ?
Also please could you paste the output of : 

```
yamllint --format parsable --strict examples/good.yml
yamllint --format parsable --strict examples/bad.yml
```

**Comment by adriens** [comment]
https://www.katacoda.com/opt-labs/courses/devops-tools/yamlfixer

waiting for good and bad to finish the scenario to showcase the autofix feature 💪 @tamere-allo-peter

**Comment by adriens** [comment]
@tamere-allo-peter 

> Could you paste the output of which yamllint ?

Yep, here it is : 

![image](https://user-images.githubusercontent.com/5235127/158084105-49aefc32-7959-488e-be54-ab04af31bed5.png)


I guess it has to deal with [`yamllint` `pip` install on step 2/5](https://www.katacoda.com/opt-labs/courses/devops-tools/yamlfixer) : 

![image](https://user-images.githubusercontent.com/5235127/158084175-9e1f14fc-d0a6-41ef-8b71-f3f599d12176.png)

**Comment by adriens** [comment]
Actually here is `requirements.txt` : 
![image](https://user-images.githubusercontent.com/5235127/158084286-899e1713-1caa-4882-a406-bf97922240f9.png)

**Comment by adriens** [comment]
Stuck on the `yamllint` install part now

**Comment by tamere-allo-peter** [comment]
@adriens you must remove PyYAML first, then if you don't succeed maybe virtualenv could help like explained [here](https://towardsdatascience.com/create-virtual-environment-using-virtualenv-and-add-it-to-jupyter-notebook-6e1bf4e03415)

**Comment by adriens** [comment]
> you must remove PyYAML first

from `requirements` ❔

**Comment by adriens** [comment]
You mean remove it **before** install requirements ?

**Comment by tamere-allo-peter** [comment]
@adriens I mean remove it entirely from your system, then proceeding with the installation of yamllint, ensuring it works, and then yamlfixer should work as expected.

**Comment by adriens** [comment]
```
$ pip uninstall PyYAML
```

leads to :

```
Found existing installation: PyYAML 3.12
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

Then, trying to apply `requirements.txt` : 

```
pip install -r requirements.txt
```

leads to : 

```
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 3.12
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by adriens** [comment]
Giving a try by using system approach

**Comment by tamere-allo-peter** [comment]
@adriens : You could always do this, as root : 

```
python3
>>> import os
>>> import shutil
>>> import yaml
>>> shutil.rmtree(os.path.split(yaml.__file__)[0])
```

This will remove PyYAML from your system. If several versions are installed, do this all over again until `import yaml` fails.

**Comment by adriens** [comment]
```
sudo apt-get -y purge python3-yaml
pip install PyYAML==6.0
```

leads to : 

```
Collecting PyYAML==6.0
  Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
Installing collected packages: PyYAML
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 3.12
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by adriens** [comment]
Je tente un passage propre avec 

```
pip install PyYAML==6.0 --ignore-installed PyYAML
```

**Comment by adriens** [comment]
That last one did the trick :fireworks: 
I'm upgrading Katacoda scenarion 


![image](https://user-images.githubusercontent.com/5235127/158263177-3f0a4085-1e71-4f15-a38b-010db357fc11.png)

**Comment by tamere-allo-peter** [comment]
@adriens Wünderbach !

**Comment by adriens** [comment]
happy to have made this through `pip` package management and not from the system side :smile_cat:

**Comment by adriens** [comment]
@tamere-allo-peter 
![image](https://user-images.githubusercontent.com/5235127/158272205-d6a8d74b-c0c7-490c-a824-222f3747aa48.png)

**Comment by adriens** [comment]
All up & running including the docker usecase :clap:
