### ISSUE TITLE
💡 Simpler version output format 💡 

### ISSUE THREAD

**Issue by adriens** [opt-nc/yamlfixer#16]
# 👉 Contexte

Actually, the `-version` output is very convenient for human but could be simpler so code/programs (unit testing, scripts automation,...) could interact with it easier.

Actually we get this : 

```
$ python3 yamlfixer --version
yamlfixer v0.1.2
```

# 💡 Feature request

As many other tools, could you instead returnas folllows (no more decoration) : 

```$ python3 yamlfixer --version
v0.1.2
```
... or add an option that adds decoration... like a verbose version of `--version` that could add : 

- full tool name
- copyright elements
- GH repo url
- ...

**Comment by adriens** [comment]
@tamere-allo-peter here are some ideas I got while interacting with `yamlfixer`

**Comment by tamere-allo-peter** [comment]
Oh yeah, you mean something like... for example... `yamlfixer --help`

;)

**Comment by tamere-allo-peter** [comment]
BTW returning the program's name as well as the version number when --version is used is  pretty standard :

ls --version
cat --version
gcc --version
python --version

to  name a few, always return the program's name and the version number.

**Comment by adriens** [comment]
Actlaly `--help` does that kind of thing : 

![image](https://user-images.githubusercontent.com/5235127/158079872-65babb61-e448-45b4-958e-d231fc4f143f.png)

**Comment by adriens** [comment]
> Oh yeah, you mean something like... for example... yamlfixer --help

AH AH, yes, exaclty 😆

**Comment by tamere-allo-peter** [comment]
I have to update the contents a bit, though...

**Comment by adriens** [comment]
Also, I'll make you an issue to get a simple content for the `--help` command.

The Katacoda scenario should also help a lot (cf #10 ) as well as embedded `yaml` samples (cf #13 )

**Comment by adriens** [comment]
Ok, let's stick with this so 👍
