### ISSUE TITLE
💡 Dedicated output section dedciated to individual Lint status 💡 

### ISSUE THREAD

**Issue by adriens** [opt-nc/yamlfixer#17]
# 👉 Context

Actually when we run `yamlfixer` command line we don't have a nice to read shell outputs `yaml` quality summary. It could be nice to get such a nice thing for the end user.

# 💡  Feature Request

Get a kind of dedicated summary section that may look like this (with emojis) : 

```
Linted files summary : 

✔️ examples/good.yml
❗    examples/bad.yml (2 issues)
```

# 💵  Benefits

- Visual and very easy to interpret
- Makes it easy to make screenshots so people share output bu dropping images in chat while working on contents... and then save time while collaborating

**Comment by adriens** [comment]
you mean... you implemented ❔ ❣️ 😮

**Comment by adriens** [comment]
Can you drop a screenshot 🙏 @tamere-allo-peter  ❔ 🤴

**Comment by tamere-allo-peter** [comment]
@adriens sure:

```
jerome@OPT17844:~/yamlfixer$ cp -r examples xx
jerome@OPT17844:~/yamlfixer$ ./yamlfixer --verbose xx/* 
Files to fix: 2
1 files successfully passed yamllint strict mode
1 files were modified
0 files were skipped
0 files were not writeable
0 files with unknown status
MODIFIED /home/jerome/yamlfixer/xx/bad.yml (handled 4/4)
  PASSED /home/jerome/yamlfixer/xx/good.yml
jerome@OPT17844:~/yamlfixer$ 
```

**Comment by adriens** [comment]
so there is no emoji ?

![image](https://user-images.githubusercontent.com/5235127/158105506-85073689-57ab-48f3-a654-e26b5a03ce92.png)

**Comment by tamere-allo-peter** [comment]
@adriens no emoji, they won't produce easily parseable output, preventing further automation. I don't know any command line tool which uses them in its output. BTW image screenshots might be nice, but are a hindrance as far as coding is concerned : you can't copy/paste their contents.

**Comment by adriens** [comment]
>  they won't produce easily parseable output, preventing further automation.

Nice shot

Would it be interesting to think about a json output to make it even easier for further integrations

**Comment by tamere-allo-peter** [comment]
@adriens json or YAML ? ;)

**Comment by adriens** [comment]
Json to embded data seems a more common pattern 😄
