### ISSUE TITLE
❔ What should `yamlfixer` command do while giving noargs❔ 

### ISSUE THREAD

**Issue by adriens** [opt-nc/yamlfixer#19]
# ❔ Context

Currenlty, running just 

`yamlfixer`

causes cli to wait for something.... forever.

# 👇 Feature request

When calling `yamlfixer` with noargs, simply return the same content as `--help` ❔

**Comment by tamere-allo-peter** [comment]
Documentation is not clear about this, sorry. If you don't specify `-` for stdin on the command line, and if there's not filename argument at all, then `-` is assumed, and input is read from stdin.

**Comment by adriens** [comment]
Perfect. I'll add this usecase in the Katacoda scenario.

Thanks fot the answer @tamere-allo-peter 👍
