### ISSUE TITLE
Katacoda scneario needs to be updated

### ISSUE THREAD

**Issue by adriens** [opt-nc/yamlfixer#24]
- [x] Document `yamlfixer --jsonsummary`
- [x] Replace `--verbose` n'existe plus, by `--summary`

**Comment by adriens** [comment]
cf #16

**Comment by adriens** [comment]
t pas impactée @mbarre sur la Gh action ?

**Comment by adriens** [comment]
Testing `--summary` option...

**Comment by adriens** [comment]
✔️ `--summary`
![image](https://user-images.githubusercontent.com/5235127/158282836-52cd8470-4084-46df-8688-0eb5314544ba.png)

![image](https://user-images.githubusercontent.com/5235127/158282878-11b97694-02dc-49b7-b75d-f49ead9cd90c.png)
![image](https://user-images.githubusercontent.com/5235127/158282918-22f046ab-c0f3-4a29-b5da-1ae7d7714faa.png)

**Comment by adriens** [comment]
Now adding an example of `--jsonsummary`

**Comment by adriens** [comment]
...

**Comment by adriens** [comment]
Now testing the whole thing...

**Comment by tamere-allo-peter** [comment]
@adriens you could also use --backup to automatically generate backup files as `*.orig`

**Comment by adriens** [comment]
@tamere-allo-peter , why does this 

```
yamlfixer --jsonsummary examples/good.yml > good.yml-summary.json
```

Create an empy file ?... while the standard output does dispaly the right contents ?

![image](https://user-images.githubusercontent.com/5235127/158284534-9125b878-ea88-4f19-857c-bc29014010c1.png)

**Comment by adriens** [comment]
how should I tune the script to make it work the way I expected it (I mean get the json in a file) 🙏 ❔

**Comment by tamere-allo-peter** [comment]
@adriens : output is sent to stderr, not stdout, that's why. Use `2>yourfile.json` to do what you want. This is done in order to not mess up with output when input is read from stdin.

**Comment by adriens** [comment]
Here it is for the `--backup` cf https://github.com/opt-nc/yamlfixer/issues/25 thanks for pointing it 👍

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/158285054-dd303bd2-29e0-4033-8149-ccb106534c2e.png)

**Comment by adriens** [comment]
All 👌

**Comment by adriens** [comment]
The scenario will be reviwed in the next days to get more feedback from developers @tamere-allo-peter

**Comment by adriens** [comment]
I'll implement the `backup` option cf #25

**Comment by tamere-allo-peter** [comment]
@adriens I don't understand what you mean, --backup works fine already no need to implement it.

**Comment by adriens** [comment]
> @adriens I don't understand what you mean, --backup works fine already no need to implement it.

I mean... make the demo in the katacoda scenario to show how useful it is

**Comment by mbarre** [comment]
> t pas impactée @mbarre sur la Gh action ?

Yes, I am but I used the previous version so my github-action still works.

**Comment by adriens** [comment]
Keep in mind to upgrade/modify the Gh Action hence 💪

**Comment by adriens** [comment]
Im' filling you a dedicated issue @mbarre

**Comment by adriens** [comment]
Issue done cf https://github.com/opt-nc/yamlfixer-action/issues/9
