### ISSUE TITLE
Refactor Katacoda install steps

### ISSUE THREAD

**Issue by adriens** [opt-nc/yamlfixer#27]
cf https://github.com/opt-nc/yamlfixer/blob/add-pypi-version-badge/README.md#-prerequisites

Install only is

```
python3 -m pip install yamlfixer-opt-nc
```

now

**Comment by adriens** [comment]
Related to #10

**Comment by adriens** [comment]
use help2man

```
sudo apt-get install help2man
help2man yamlfixer >yamlfixer.1
sudo cp yamlfixer.1  /usr/share/man/man1
man yamlfixer
````

**Comment by tamere-allo-peter** [comment]
@adriens the pip setup script should take care of this, not sure if it is still possible with recent versions using setuptools, I did this ages ago using distutils and it was feasible. I'll check this ASAP.

**Comment by adriens** [comment]
@tamere-allo-peter  : Hopefully I should work on this tomorrow morning

**Comment by adriens** [comment]
Working on it rght now 🚀

**Comment by adriens** [comment]
Première review en cours suite au refactoring...

**Comment by adriens** [comment]
Première review en cours suite au refactoring...

**Comment by adriens** [comment]
I'm facing an issue appeared on the `latest` version of the docker image cf https://github.com/opt-nc/yamlfixer/issues/29

**Comment by adriens** [comment]
I'm waiting for the issue to be fixed to achieve the refactoring.

**Comment by adriens** [comment]
⏸️

**Comment by adriens** [comment]
Thanks for current review and alerts on typos @tamere-allo-peter

**Comment by adriens** [comment]
Back to waiting for https://github.com/opt-nc/yamlfixer/issues/29

**Comment by adriens** [comment]
⏸️

**Comment by adriens** [comment]
Review process with collaborators in the pipe 🚀

**Comment by adriens** [comment]
Review status : 1/3 ✔️

**Comment by adriens** [comment]
Fxied
