### ISSUE TITLE
💡 ANSI color in console output 💡 

### ISSUE THREAD

**Issue by adriens** [opt-nc/yamlfixer#38]
In the log outuput it would be cool to get the log output colorized according to the lint/fix status : 

- `green` : nothing had to be done
- `orange` : fixes have been done
- `red` : lint did not pass and no fix could be applied : human intervention required

**Comment by tamere-allo-peter** [comment]
![colorsummary](https://user-images.githubusercontent.com/85658105/158707639-60879b0b-f838-4889-bd33-df3984edec9b.png)

**Comment by adriens** [comment]
Hello beauty 💟

**Comment by adriens** [comment]
You mean .... you have released it ❔ ❣️

**Comment by tamere-allo-peter** [comment]
It seems to be the case :)

**Comment by adriens** [comment]
🎅

**Comment by adriens** [comment]
Seems like I can't see the colors on Katacoda : 

![image](https://user-images.githubusercontent.com/5235127/158722138-4cd711fe-bd11-4769-8e22-7c09bbb1e5e5.png)

**Comment by adriens** [comment]
Whereas I can get colors while using other command line tools

**Comment by tamere-allo-peter** [comment]
@adriens : try again with --colorsummary

**Comment by tamere-allo-peter** [comment]
@adriens it might become the default with --summary and have --colorsummary disappear, not sure yet...

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/158722674-bdc39304-f3af-4dd8-9c6f-d37dcb6fb784.png)

**Comment by adriens** [comment]
> @adriens it might become the default with --summary and have --colorsummary disappear, not sure yet...

I would keep only `--summary` ... which would reply with colors (that's what I would expect)

**Comment by tamere-allo-peter** [comment]
Yeah you're probably right...

**Comment by tamere-allo-peter** [comment]
BTW the current implementation doesn't works as you might expect, since if no fix could be done the file is considered as SKIPPED, which is different from the red ERROR status (mostly write permissions problem).

**Comment by adriens** [comment]
I'm performing tests on Windows cf #41 ...

**Comment by adriens** [comment]
Surprinsigl it works on windows DOS command... but not on gith bash cf #43

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/158758388-6f859cd7-ccbd-4031-913d-cd03e98b852c.png)
