### ISSUE TITLE
🛡️ Security 🛡️ 

### ISSUE THREAD

**Issue by adriens** [opt-nc/yamlfixer#46]
Activate security with CodeQL and GHAS (as part of the CI)

**Comment by adriens** [comment]
Actually looks pretty good @tamere-allo-peter  @mbarre : 

![image](https://user-images.githubusercontent.com/5235127/159186186-371cc0df-63db-4604-92fd-da0c7dc633e1.png)

**Comment by mbarre** [comment]
y a plus rien a faire sur ce ticket @adriens, si ?

**Comment by adriens** [comment]
ben en fat @tamere-allo-peter  a mergé et :ok_hand:
