### ISSUE TITLE
🤖 CI > branch protection and package delivery 📦 

### ISSUE THREAD

**Issue by adriens** [opt-nc/yamlfixer#47]
- [x] #54
- [x] Protect `main` with ci

**Comment by tamere-allo-peter** [comment]
Tagged commits will be automatically pushed to PyPi from 0.3.7 onwards.

**Comment by adriens** [comment]
Now, protecting branches would be a good thing, don't you think so ?

**Comment by tamere-allo-peter** [comment]
Yes, both the YAML (workflows) and Python code should be automatically linted from CI first, then I'll add branch protection just like for our ansible roles and playbooks.

**Comment by adriens** [comment]
Awesome :clap:

**Comment by tamere-allo-peter** [comment]
@adriens branch protection is now active on main. YAML files are firtst linted with yamllint, then Python files are linted successively with flake8 then with pylint.
If linting is successfull, a PR is automatically created and merged.
Next step is to include automated testing framework in this process.

**Comment by adriens** [comment]
Great job @tamere-allo-peter and auto-merge :muscle:
