### ISSUE TITLE
Push to pypi through ci

### ISSUE THREAD

**Issue by adriens** [opt-nc/yamlfixer#54]

**Comment by adriens** [comment]
You managed to use GH secrets at the repo level @tamere-allo-peter :grey_question:

**Comment by tamere-allo-peter** [comment]
@adriens : yes. See .github/workflows/publish_pypi.yml

**Comment by tamere-allo-peter** [comment]
@adriens : seems to work fine, you can close it IMHO.

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/158907521-3ca1cd38-1c6b-486f-b0d3-695af53ddac1.png)
