### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by tamere-allo-peter** [opt-nc/yamlfixer#60]
# 1️⃣ Description

To fix a problem, `yamlfixer` often has to get the indentation of the previous (or next) line to align the current line relatively to the previous one. However if the previous (or next) line is empty, this may cause problems instead of fixing them.

# 2️⃣ Expected behavior

Instead, `yamlfixer` should first search upward for the first non-blank line, and only then get its indentation level.

# ℹ️ Environment details

 - OS: N/A
 - Python runtime : N/A
 - The output of `yamlfixer --version` : N/A
 - Used shell (Git bash, `bash`, `zsh`, `MS DOS`, ...) : N/A

**Comment by adriens** [comment]
:muscle:
