### ISSUE TITLE
Feature request > Simpler install process on linux (no need to add to PATH)

### ISSUE THREAD

**Issue by adriens** [opt-nc/yamlfixer#63]
# 📜 Read (and accept) this before

- [x] I am respectful : this is free software and efforts are made on free time, with 💙
- [x] I have looked at the current [project roadmap](https://github.com/opt-nc/yamlfixer/projects/1)
- [x] I have already looked in current and past issues so I'm sure others did not already push a simlar issue
- [x] I make one single issue per feature request so the team can work efficienlty on it
- [x] I am aware of [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) : **Make each program do one thing well**
- [x] When (and if) your feature is implemented, be thankful and help promote the project by sharing the issue on social networks (twitter, linkedIn, dev.to...) and dropping the url on te issue
  

# ❔ Context

Detail the current situation/difficultes or problem you are facing and how you think `yamlfixer` could help : 

Actually, the install process need to update the PATH so `yamlfixer` can be found` : 

```shell
python3 -m pip install yamlfixer-opt-nc
export PATH=$PATH:~/.local/bin
yamlfixer --version
```

# 💡 Proposed solution

I would like people not have to update path to get a more straightforward install process.

**Comment by tamere-allo-peter** [comment]
@adriens : that is not exact. What is exact is to say that if you install as an ordinary user (vs installing as root) then on some systems `~/.local/bin` might not be your `PATH`.

See the discussion and reasoning at https://github.com/pypa/pip/issues/3813

It's old now, so recent systems should already include `~/.local/bin` in your `PATH` for you.
Per their reasoning, and I agree with it, manually modifying `~/.bashrc` or `~/.profile` to modify `PATH` once for all is a better option than modifying it automatically.

I suggest we won't fix this.

**Comment by tamere-allo-peter** [comment]
@adriens BTW `pipx ensurepath` does what you want. Refs #64.

**Comment by adriens** [comment]
> @adriens BTW pipx ensurepath does what you want.

Yep, that's why I finallly created a dedicated `pipx` issue as the tool really is dedciated to pakcaging apps :muscle:
