### ISSUE TITLE
Prune head branches

### ISSUE THREAD

**Issue by adriens** [opt-nc/yamlfixer#69]
# ❔ Context

Most branches have been merged, but they still remain which makes the source code look a bit messy.

I have updated settings so this won't occur in the future : 

![image](https://user-images.githubusercontent.com/5235127/159368811-449d60e3-5cdb-4c25-9f52-f9ff04d8e37c.png)

Still for old ones it has to be done mnually :

![image](https://user-images.githubusercontent.com/5235127/159368664-5e1ae443-101e-4a7c-9cb7-c14f6788f291.png)

# 🎯 Target

- Keep only active branches

# 💰 Gains

What are the gains of implementing this issue for this project.

- Easier to manage source code

# ⚠️ Risks

- Make error while dealing /managing  branches

**Comment by tamere-allo-peter** [comment]
Done

**Comment by adriens** [comment]
:zap: 
![image](https://user-images.githubusercontent.com/5235127/159369757-1cd842a3-43fe-45ce-95b4-e60991e51542.png)
