### ISSUE TITLE
Feature request > Customize backup files suffix pattern

### ISSUE THREAD

**Issue by adriens** [opt-nc/yamlfixer#70]
# 📜 Read (and accept) this before

- [x] I am respectful : this is free software and efforts are made on free time, with 💙
- [x] I have looked at the current [project roadmap](https://github.com/opt-nc/yamlfixer/projects/1)
- [x] I have already looked in current and past issues so I'm sure others did not already push a simlar issue
- [x] I make one single issue per feature request so the team can work efficienlty on it
- [x] I am aware of [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) : **Make each program do one thing well**
- [x] When (and if) your feature is implemented, be thankful and help promote the project by sharing the issue on social networks (twitter, linkedIn, dev.to...) and dropping the url on te issue
  

# ❔ Context

Detail the current situation/difficultes or problem you are facing and how you think `yamlfixer` could help : 

:point_right: Actuallu the `--backup` option only generated `.org` file extension : for sose usecases it would be convenient to be able to customize that (instead of having to manually copy files).

# 💡 Proposed solution

Detail here what you would like `yamlfixer` to do to help on the problematic.

- add a `--backsupsuffix` option so end user can customize backup files inside `yamlfixer` options

**Comment by adriens** [comment]
Released in [0.4.1](https://github.com/opt-nc/yamlfixer/releases/tag/0.4.1) :clap:  @tamere-allo-peter

**Comment by tamere-allo-peter** [comment]
@adriens actually it's better to use [0.4.2](https://github.com/opt-nc/yamlfixer/releases/tag/0.4.2) because there was a bug in the previous one :-(

**Comment by adriens** [comment]
ANy way the future has been released :pray:

**Comment by adriens** [comment]
No more unaesthetic `cp` commands... :+1:

**Comment by adriens** [comment]
@tamere-allo-peter  Here it is :fireworks: 
 
[![asciicast](https://asciinema.org/a/479510.svg)](https://asciinema.org/a/479510)

**Comment by adriens** [comment]
:bird: [Tweet](https://twitter.com/rastadidi/status/1506041727555039233) :rocket:
