### ISSUE TITLE
Make tabsize configurable and replace all tabs

### ISSUE THREAD

**Issue by tamere-allo-peter** [opt-nc/yamlfixer#72]
# ❔ Context

When dealing with incorrect YAML files containing tabs, currently `yamlfixer` replaces the first tab reported by `yamllint` with a single space, which often doesn't do what is needed to fix the problem.

Having a configurable tab size, and ensuring that `yamlfixer` replaces all tabs on a faulty line with the corresponding number of spaces would be great.

# 🎯 Target

Add a --tabsize command line option and use that value to replace all tabs.

# 💰 Gains

- Improve the output quality

# ⚠️ Risks

- Stay with an incorrect behavior

**Comment by adriens** [comment]
⚡
