### ISSUE TITLE
Feature request > Configure input command from file

### ISSUE THREAD

**Issue by adriens** [opt-nc/yamlfixer#74]
# 📜 Read (and accept) this before

- [x] I am respectful : this is free software and efforts are made on free time, with 💙
- [x] I have looked at the current [project roadmap](https://github.com/opt-nc/yamlfixer/projects/1)
- [x] I have already looked in current and past issues so I'm sure others did not already push a simlar issue
- [x] I make one single issue per feature request so the team can work efficienlty on it
- [x] I am aware of [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) : **Make each program do one thing well**
- [x] When (and if) your feature is implemented, be thankful and help promote the project by sharing the issue on social networks (twitter, linkedIn, dev.to...) and dropping the url on te issue
  

# ❔ Context

Detail the current situation/difficultes or problem you are facing and how you think `yamlfixer` could help : 

👉  Actually we neeed to call a command line to run a `yamlfixer` command.

... but in some cases, it is possible that we could have to always run the same command with the same parameters from the same directory.

# 💡 Proposed solution

Detail here what you would like `yamlfixer` to do to help on the problematic.

In that case, the command line can be historized/versioned for example in CI scenarios.

it could looke like that : 

```shell
yamlfixer --conf PATH_TO_YMLFXR_CONF
```

All parameters could be put in the conf file.. probably as simple `yml` file so it could be linted itsefl by  `yamlfixer` and also deal with potential hierarchical parameters.

By default ` .yamllint` could be the conf file (thanks for pointing this @tamere-allo-peter 👍 )

# 📑 Linked resources

- [How `gomplate` implements that](https://docs.gomplate.ca/config/)

**Comment by adriens** [comment]
Feature being actually discussed with @tamere-allo-peter  and @mbarre

**Comment by tamere-allo-peter** [comment]
@adriens no _.yamllint_ can't be the conf file, I meant _.yamlfixer_

Anyway currently `yamlfixer` doesn't have many configuration options, so instead I propose allowing it to read all or parts of the command line arguments from a file, using the well-known `@argsfilename` syntax : 

```shell
$ cat arguments
--summary
xx/fakeansiblevault.yml
xx/bad.yml
xx/good.yml
xx/withtabs.yml

$ yamlfixer --jsonsummary @arguments
usage: yamlfixer [-h] [-v] [-b] [-B BACKUPSUFFIX] [-d] [-l] [-j | -p | -s] [-t TABSIZE] [file [file ...]]
yamlfixer: error: argument -s/--summary: not allowed with argument -j/--jsonsummary

$ yamlfixer @arguments <examples/bad.yml
---
name: Build HelloYaml

# yamllint disable-line rule:truthy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with Maven
        run: mvn package
Files to fix: 5
1 files successfully passed yamllint strict mode
3 files were modified
1 files were skipped
0 files were not writeable
0 files with unknown status
 SKIPPED /home/jerome/yamlfixer/xx/fakeansiblevault.yml
MODIFIED /home/jerome/yamlfixer/xx/bad.yml (handled 4/4)
  PASSED /home/jerome/yamlfixer/xx/good.yml
MODIFIED /home/jerome/yamlfixer/xx/withtabs.yml (handled 1/1)
MODIFIED <stdin> (handled 4/4)
```

**Comment by tamere-allo-peter** [comment]
@adriens not sure if a new release is needed for this, as I thought it was either already working or a very quick fix, and in reality it was a one-liner...

**Comment by adriens** [comment]
So it was working with this approach.

>  not sure if a new release is needed for this, as I thought it was either already working or a very quick fix, and in reality it was a one-liner...

If it's the case, yep, no need for a new reelase :+1:

**Comment by adriens** [comment]
... maybe a dedicated entry in the README could help :grey_question:

**Comment by tamere-allo-peter** [comment]
Just released with this dedicated entry.

**Comment by adriens** [comment]
Let me have a :eyes:

**Comment by adriens** [comment]
Could you be more specific eg. with : 

- a dedicated subsection
- a pseudo code example

As for now it's not that easy for me to understad how to use this feature  : 

![image](https://user-images.githubusercontent.com/5235127/159593385-8bf2d2d5-0015-4963-8d7d-1f0c479ad0c6.png)


Next, I'll create a dedicated `asciinema` tuto cf #62

**Comment by adriens** [comment]
:pray:

**Comment by adriens** [comment]
:rocket:
