### ISSUE TITLE
Add a -n|--nochange command line option

### ISSUE THREAD

**Issue by tamere-allo-peter** [opt-nc/yamlfixer#77]
# ❔ Context

To simplify diagnostic operations on YAML files, it would be great if `yamlfixer` implemented a simulation mode, which would output the correct summary and exit code, but would not modify any file.

# 🎯 Target

Implement a `-n|--nochange` command line option.

# 💰 Gains

Having a way to diagnose the fixing of problems without needing to modify input files.

# ⚠️ Risks

None

**Comment by adriens** [comment]
Great :bulb:

**Comment by tamere-allo-peter** [comment]
Very useful !
