### ISSUE TITLE
Yamlfixer version in Docker image is not always the good one

### ISSUE THREAD

**Issue by mbarre** [opt-nc/yamlfixer#81]
# 1️⃣ Description

Yamlfixer version is not set in Dockerfile when yamlfixer is released.
Yamlfixer version installed is not the last, but the version before. 

Reason: 
The publication of the new version on pip registry is done after the docker image build and publish.

## 📑 Steps to Reproduce

```shell
docker pull optnc/yamlfixer:0.4.8
docker image ls
REPOSITORY                                        TAG                 IMAGE ID       CREATED             SIZE
optnc/yamlfixer                                   0.4.8               693169d2843d   About an hour ago   74.6MB

❯ docker run -i -t --name yamlfixer_0.4.8 --rm 693169d2843d /bin/sh
/ # yamlfixer --version
yamlfixer v0.4.7
```

# 2️⃣ Expected behavior

yamlfixer --version should return v.0.4.8

 
# Additional context

Pip publication is done on release only, whereas docker image publication is done on push too. So, tag "latest" on docker image doesn't contains the latest version of the yamlfixer.

**Comment by tamere-allo-peter** [comment]
This is due to the `publish_pypi.yml` workflow being launched in parallel to `publish_docker_hub.yml` and taking much longer to execute, so the PyPi package is not available yet when `publish_docker_hub.yml` needs it.

**Comment by tamere-allo-peter** [comment]
This could help : https://stevenmortimer.com/running-github-actions-sequentially/

**Comment by adriens** [comment]
Nice ticket @mbarre 👍

**Comment by tamere-allo-peter** [comment]
The solution is for publish_pypi.yml to notify GitHub that publish_docker_hub.yml should be run again. This is probably the least intrusive solution. There will be two successive publications on Docker Hub, but who cares ?

**Comment by tamere-allo-peter** [comment]
And here's how to do : https://docs.github.com/en/actions/using-workflows/reusing-workflows

**Comment by tamere-allo-peter** [comment]
@mbarre so unfortunately I think publish_docker_hub.yml needs some modifications to make it re-usable from pubish_pypi.yml

**Comment by adriens** [comment]
The docker push strategy i s quite simple and classical : 

- push to `main` -> create a `latest` tag on DockerHub
- push a GH release/tag -> creates a `stabke` and `vX` on on DockerHub

So Docker images push strategy stays very simple and all software gets released at the same pace

**Comment by tamere-allo-peter** [comment]
@adriens I don't think doing the same would be possible for PyPi, because uploading a duplicate (`...-latest`) is not allowed there.

**Comment by adriens** [comment]
:open_mouth: We'll have a tlk about that as the underlying technology should not impact the way we release/deliver software :smile_cat:

**Comment by tamere-allo-peter** [comment]
@mbarre, @adriens : please could you double check I didn't introduce a regression wrt issue #81 when I added branch restrictions ? As of now the latest Docker image should contain yamlfixer v0.6.5, please get back to me ASAP if that's not the case.
