### ISSUE TITLE
Feature request > Accept directories and add a recursive mode

### ISSUE THREAD

**Issue by tamere-allo-peter** [opt-nc/yamlfixer#82]
# 📜 Read (and accept) this before

- [x] I am respectful : this is free software and efforts are made on free time, with 💙
- [x] I have looked at the current [project roadmap](https://github.com/opt-nc/yamlfixer/projects/1)
- [x] I have already looked in current and past issues so I'm sure others did not already push a simlar issue
- [x] I make one single issue per feature request so the team can work efficienlty on it
- [x] I am aware of [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) : **Make each program do one thing well**
- [x] When (and if) your feature is implemented, be thankful and help promote the project by sharing the issue on social networks (twitter, linkedIn, dev.to...) and dropping the url on te issue
  

# ❔ Context

Detail the current situation/difficultes or problem you are facing and how you think `yamlfixer` could help : 

It might be useful for `yamlfixer` to accept directories names on the command line, and to automatically search for `YAML` files in these directories based on a preset but modifiable list of filename extensions. Adding an option to make this behavior recursive would be even better.

# 💡 Proposed solution

Detail here what you would like `yamlfixer` to do to help on the problematic.

1. Accept directories on the command line
2. Add a `-e|--extension EXT` command line option, with `EXT` being a comma separated list of acceptable filename extensions to search for in directories, and defaulting to `yml,yaml,yamllint`
3. Add a `-r|--recurse LEVEL` command line option, with `LEVEL` defaulting to `0` (i.e. no recursion), and accepting any positive integer value to set the limit level, or `-1` to not set any limit.
4. Make `yamlfixer` search for files matching this set of extensions from each of the directories passed on the command line, up to the recursion level which was asked for.

**Comment by adriens** [comment]
🎆
