### ISSUE TITLE
The patch file created with --diffto doesn't always work

### ISSUE THREAD

**Issue by tamere-allo-peter** [opt-nc/yamlfixer#86]
# 1️⃣ Description

When a badly formatted YAML file is missing a newline on the very last line, and when using the `--diffto` command line option to generate a `diff` file, the generated `diff` file is broken wrt that particular file : it can't be applied as-is with the `patch` command.

This seems to be due to how `yamlfixer` reads its input files and removes all newlines to add them back at dump time.

Probably not that easy to fix...

## 📑 Steps to Reproduce

```shell
jerome@OPT17844:~/yamlfixer$ yamlfixer --version
yamlfixer v0.6.0

jerome@OPT17844:~/yamlfixer$ yamlfixer --nochange --diffto uni.patch examples/

jerome@OPT17844:~/yamlfixer$ patch -p0 <uni.patch
patching file examples/bad.yml
patching file examples/fakeansibleplaybook.yml
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file examples/fakeansibleplaybook.yml.rej
patching file examples/withtabs.yml

jerome@OPT17844:~/yamlfixer$ 
```

We can clearly see the patch failing for the second file, i.e. the one that is missing the newline at EOL. The two other patches in the `diff` file are applied correctly.

# 2️⃣ Expected behavior

The generated `diff` file should work out of the box in all cases.

**Comment by adriens** [comment]
In the next weeks I'l try to implement cli tests that may help documenting that kind of beahvior :crossed_fingers:

**Comment by tamere-allo-peter** [comment]
Works fine now.
